---
title: "Adding cluster info"
output: html_notebook
---


```{r}
library(Seurat)
library(ggplot2)
library(viridis)
library(dplyr)
library(pheatmap)
```

# Load all seurat objects
```{r}
seurat <- readRDS( "C:/.../Full dataset.rds")
epithelial <- readRDS("C:/.../Epithelial_final.rds")
stromal <- readRDS("C:/.../Stromal_final.rds")
endothelial <- readRDS("C:/.../Endothelial.rds")
immune <- readRDS("C:/.../Immune.rds")
PNEC <- readRDS("C:/.../PNEC.rds")
pericytes <- readRDS("C:/.../PDGFRB+.rds")
ciliated <- readRDS("C:/.../Ciliated.rds")
``` 


# Add broad clusters to subsets
```{r}
epithelial$broad.cluster <- Idents(seurat)[colnames(epithelial)]
stromal$broad.cluster <- Idents(seurat)[colnames(stromal)]
endothelial$broad.cluster <- Idents(seurat)[colnames(endothelial)]
immune$broad.cluster <- Idents(seurat)[colnames(immune)]
PNEC$broad.cluster <- Idents(seurat)[colnames(PNEC)]
PDGFRB+$broad.cluster <- Idents(seurat)[colnames(PDGFRB+)]
ciliated$broad.cluster <- Idents(seurat)[colnames(ciliated)]
```


```{r}
DimPlot(epithelial, group.by="broad.cluster")
DimPlot(stromal, group.by="broad.cluster")
DimPlot(endothelial, group.by="broad.cluster")
DimPlot(immune, group.by="broad.cluster")
DimPlot(PNEC, group.by="broad.cluster")
DimPlot(PDGFRB+, group.by="broad.cluster")
DimPlot(ciliated, group.by="broad.cluster")
```

```{r}
saveRDS(epithelial, file = "C:/.../Epithelial_final.rds")
saveRDS(stromal, file = "C:/.../Stromal_final.rds")
saveRDS(endothelial, file = "C:/.../Endothelial.rds")
saveRDS(immune, file = "C:/.../Immune.rds")
saveRDS(PNEC, file = "C:/.../PNEC.rds")
saveRDS(PDGFRB+, file = "C:/.../PDGFRB+.rds")
saveRDS(ciliated, file = "C:/.../Ciliated.rds")
```


# Add high-resolution clusters to full seurat
```{r}
epithelial_clusters <- data.frame(cell = colnames(epithelial),
                                  cluster = paste0("Epithelial_", 
                                                   epithelial$seurat_clusters))
stroma_clusters <- data.frame(cell = colnames(stromal),
                                  cluster = paste0("Stroma_", 
                                                   stromal$seurat_clusters))
endothelial_clusters <- data.frame(cell = colnames(endothelial),
                                  cluster = paste0("Endothelial_", 
                                                   endothelial$seurat_clusters))
immune_clusters <- data.frame(cell = colnames(immune),
                                  cluster = paste0("Immune_", 
                                                   immune$seurat_clusters))
PNEC_clusters <- data.frame(cell = colnames(PNEC),
                                  cluster = paste0("PNEC_", 
                                                   PNEC$seurat_clusters))
PDGFRB+_clusters <- data.frame(cell = colnames(pericytes),
                                  cluster = paste0("PDGFRB+_", 
                                                   PDGFRB+$seurat_clusters))
ciliated_clusters <- data.frame(cell = colnames(ciliated),
                                  cluster = paste0("Ciliated_", 
                                                   ciliated$seurat_clusters))
all_clusters <- bind_rows(epithelial_clusters, stroma_clusters, endothelial_clusters,
                          immune_clusters, PNEC_clusters, pericytes_clusters, ciliated_clusters)
```

```{r}
seurat$cluster_high_res <- "Doublet"
seurat$cluster_high_res[match(all_clusters$cell, colnames(seurat))] <- all_clusters$cluster
```
```{r}
DimPlot(seurat, group.by = "cluster_high_res")
```


# Remove doublets & add cell types
```{r}
annotation <- read.csv("C:/..../cluster_annotations.csv",
                       stringsAsFactors = F)
annotation <- annotation[,1:3]
annotation$tmp <- paste0(annotation$Subtype, "_", annotation$Cluster)
```

```{r}
seurat$CellType2 <- "Doublet"
seurat$CellType2 <- annotation$Cell.type2[match(seurat$cluster_high_res, annotation$tmp)]
```

Remove doublets
```{r}
cells_keep <- colnames(seurat)[seurat$CellType2 != "Doublet"]
```
```{r}
seurat <- subset(seurat, cells = cells_keep)
```
```{r}
DimPlot(seurat, group.by = "CellType2", label = TRUE)
```

```{r}
saveRDS(seurat, file="C:/.../Full dataset_annotated detailed clusters.rds")
```


